### ISSUE TITLE
Currently there is a prob of binary update.

### ISSUE THREAD

**Issue by akhilmhdh** [akhilmhdh/contributors-readme-action#1]

**Comment by thedavidprice** [comment]
I might be encountering this issue -- when the Action runs, my README becomes an un-displayable binary file. Was that happening with this bug originally? If so, curious about the solution.

**Comment by akhilmhdh** [comment]
@thedavidprice Hi david. Wow can u please tell me how the issue happened . I would love to solve the bug. Like how anyway for me to reproduce.

**Comment by thedavidprice** [comment]
@akhilmhdh thanks for the reply! I think it might have to do with our use of HTML tags at the top of the README (for an image logo header). Let me diagnose a bit further and then I'll open up a proper issue if needed.

**Comment by akhilmhdh** [comment]
@thedavidprice cool. I would be happy to help you. Ok ill close this issue, definitely open an issue when you find the bug. 

Background: This issue one time came for my create-react-app generated readme but later when I tried it was working. So i think its caused by a specific encoding something like that.
