### ISSUE TITLE
Sponsors / Weights

### ISSUE THREAD

**Issue by alandefreitas** [akhilmhdh/contributors-readme-action#12]
Hi! Thanks for the action!

Is it possible to also add sponsors to the list? 
On one hand, it could do that only by also querying ${sponsors}, right?

```js
```

On the other hand, that might create some small conflict with https://github.com/akhilmhdh/contributors-readme-action/issues/9, since we would now have to weight sponsors/contributors to put them in order. And I think https://github.com/akhilmhdh/contributors-readme-action/issues/9 is crucial because contributions are likely to follow a Pareto distribution.

I can help with any of these things if you want.

Thanks,

**Comment by akhilmhdh** [comment]
Hi @alandefreitas 😄 
. The sponser was a really good idea consider it done by this week itself. So i have been thinking about other issue. The other one I have a doubt what if I make the contributors into two categories. Like one for core team members and one for other contributors. Can you give your opinion about it, like would it be a nice feature to be added.

**Comment by alandefreitas** [comment]
@akhilmhdh I pushed "command" before I finished writing. I thought I had canceled and just noticed I created two issues. Sorry about that. There's the other issue: https://github.com/akhilmhdh/contributors-readme-action/issues/13
