### ISSUE TITLE
Error: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by alandefreitas** [akhilmhdh/contributors-readme-action#16]
Hey @akhilmhdh,

I think I found a bug somewhere.

Everything was working perfectly until a few hours ago but now I'm getting [this error](https://github.com/alandefreitas/mdsplit/runs/1200676104?check_suite_focus=true#step:2:12):

```
Run akhilmhdh/contributors-readme-action@v2.0
  with:
    image_size: 100
    columns_per_row: 6
    readme_path: README.md
    collaborators: direct
    commit_message: contrib-readme-action has updated readme
    committer_username: contrib-readme-bot
    committer_email: contrib-readme-action@noreply.com
  env:
    GITHUB_TOKEN: ***
Error: Cannot read property 'split' of null
```

It seems to have something to do with the "actions-user" "contributor". That seems to be the only thing that has changed.

**Comment by akhilmhdh** [comment]
Hey @alandefreitas yup. The issue happened by an accident of my assumption that all GitHub users has a name which was false. Really sorry about that. I have released a new patch so use v2.0.1. 

https://github.com/akhilmhdh/contributors-readme-action/issues/15

**Comment by alandefreitas** [comment]
I'm sorry I didn't see the patch. My bad. 😔

**Comment by alandefreitas** [comment]
The actions-user is going to the collaborators sections though. 
https://github.com/alandefreitas/mdsplit#developers
I think it's a bot github doesn't officially classify as a bot. 🙃
