### ISSUE TITLE
Remove contributors

### ISSUE THREAD

**Issue by alandefreitas** [akhilmhdh/contributors-readme-action#17]
Hi @akhilmhdh ,

Me again. 😆  

Is there an option to remove specific contributors from the list?
The reason is that the "Actions-user" is considered a "contributor", and not a bot:
https://alandefreitas.github.io/matplotplusplus/contributing/contributors.html

At first, I was just going to leave it there. But I noticed that, because the bot is working every time anyone pushes something, it will quickly become the most active contributor by far. 😂 That's kind of weird.

Sorry to be using issues for questions, but that might be kind of a feature request depending on what you think.

**Comment by akhilmhdh** [comment]
lol @alandefreitas sorry man. I was working on a DL project on past two days. So was busy. Anyways actually I solved your issue its not about removing. It was my mistake in which i forgot remove bots from collaborators and add them to bots list. I have done it and released a new patch v2.0.2. Try it and if it solved please close this issue.

**Comment by alandefreitas** [comment]
I updated to v2.0.2 but "Actions-user" is still there.
https://github.com/alandefreitas/mdsplit#developers

Not sure, but I think  "Actions-user" is a username people use in some actions but github doesn't really consider it a bot.

It's the username I use for updating the docs from an action:
https://github.com/alandefreitas/mdsplit/blob/25186280f4da22764603430cd43f5f3b96af2c53/.github/workflows/docs.yml#L39
I don't know if I should be using another username to explicitly inform this is a bot, but I had a look at other repositories and it seems like everyone else also uses "Actions-user". 

I think I've seen "Actions-user[bot]" somewhere once, but I don't know if that makes a difference. It wouldn't remove the old "Actions-user" as a contributor anyway.

**Comment by akhilmhdh** [comment]
@alandefreitas did u removed old data. I am actually using the old template to reuse it again to speed up the action. Can you just remove old data and run the action

**Comment by alandefreitas** [comment]
Mmm... I had no idea.

Anyway, I removed the whole table:
https://github.com/alandefreitas/mdsplit/commit/188c897559a04738f7f93e9ecf006f40ffa1528e

Actions-user updated the docs for me:
https://github.com/alandefreitas/mdsplit/commit/4bafc14d3ac6519823480c7b04db6cf8bd8e2bcf

An contrib-readme-bot update the README.md and included Actions-user back in there.
https://github.com/alandefreitas/mdsplit/commit/7c4f8ea2ae771f6847651cdffb7c7934dc39f4e2

**Comment by akhilmhdh** [comment]
mmmm..interesting. I think I should probably use the action and see whats going on in it. Will ping you on new update 😄

**Comment by akhilmhdh** [comment]
@alandefreitas Check the new [v2.1](https://github.com/marketplace/actions/contribute-list) I have fixed this bug for you. Moved the actions-user to bots list. If it solves it kindly close the issue, else definitely comment here.

**Comment by alandefreitas** [comment]
Thanks!

**Comment by NullVoxPopuli** [comment]
did I type this wrong? https://github.com/universal-ember/ember-primitives/blob/main/README.md?plain=1#L16
