### ISSUE TITLE
Only run when contributors change

### ISSUE THREAD

**Issue by EmilStenstrom** [akhilmhdh/contributors-readme-action#20]
As of now the contributor-readme-bot runs on each commit or merge. Would it be possible to only run it when the list of contributor actually changes? The annoying part of it running all the time is that making two quick commits and pushes locally fails, since contributor-readme-bot gets in between them. Not sure if I'm making sense.

Thank you for a great bot, really helps push the community part of open source!

**Comment by akhilmhdh** [comment]
@EmilStenstrom ohhhhh really. That's a bug then I guess. Cause I trigger commit only when the readme needs to be changed. By comparing base64 of original readme and formatted one. So I am assuming there must have happened a bug. Definitely will check it. Give me two days, cause currently in another work 😢 . But will fix it asap.

Also tysm for your kind words. Much appreciated 😄

**Comment by EmilStenstrom** [comment]
Ah, that makes sense. But then the bot will run when the README is changed for other reasons. I think that's what happened to me. I thought it ran on every commit, but the commits I looked at was other changes to README.

**Comment by akhilmhdh** [comment]
But still its an annoying thing agreed. I'll definitely look into this and find a solution. ✌🏽

**Comment by akhilmhdh** [comment]
@EmilStenstrom Can u please tell me a way to reproduce this bug. I have solved other two bugs. So planning to solve this one also in this patch

**Comment by EmilStenstrom** [comment]
I thought the action was run each time the README was changed? In that case, changing the README should trigger it?

**Comment by akhilmhdh** [comment]
@EmilStenstrom  I did made a change to readme's other parts. But it waas working fine. the bot didn't updated it.

**Comment by EmilStenstrom** [comment]
Ah, so maybe it was the newline change that triggered it? That would make sense because it was technically between the comments. Thank you for your hard work! :)
