### ISSUE TITLE
Error in Actions

### ISSUE THREAD

**Issue by Maniacxxx** [akhilmhdh/contributors-readme-action#21]
![image](https://user-images.githubusercontent.com/52683414/108394477-bfd6b900-71e2-11eb-96c4-db193688035e.png)

`Error: Could not resolve to a User with the login of 'KNOWLDGE'.`

It's saying that KNOWLDGE is a User, not an Organization.

**Comment by akhilmhdh** [comment]
@Maniacxxx Sorry for late response. Oh that's a good find. Ill try to reproduce it and fix it  asap. So sorry for the bug. Give me some time. Running on a bit tight schedule.

**Comment by akhilmhdh** [comment]
@Maniacxxx   Hey there. [contributors-readme-action v2.1.1](https://github.com/marketplace/actions/contribute-list) has been released and fixed these bugs. Kindly update your workflow file. 

Tysm for using this action and your feedbacks are much appreciated. For future release and also if you have liked the bot, kindly give a star ⭐ ( makes me also happy 😅) .

Closing this issue. Feel free to open it, if it didn't solved.

**Comment by Maniacxxx** [comment]
Thank you, it works now! Love the project I'll be sure to star it!
