### ISSUE TITLE
Messing up encoding of á to C

### ISSUE THREAD

**Issue by EmilStenstrom** [akhilmhdh/contributors-readme-action#22]
The bot seems to mess up the encoding when changing the README file. An á used outside of the bot's contrib comment is changed to (something that looks like, I haven't verified that it isn't some strange unicode char) a C:

Here's an example: https://github.com/EmilStenstrom/django-components/commit/63a63815e1df29b558a021bb419d37ce2cd92b76#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R169

**Comment by akhilmhdh** [comment]
@EmilStenstrom i think this issue is due to my conversion from base64( contents are given from github api using base64 ) to ascii conversion. I was using utf-8 and there was a good reason why i shifted it to ascii though. Forgot the reason though. But ill find a solution on this.

**Comment by akhilmhdh** [comment]
Will release a patch soon :smile:

**Comment by akhilmhdh** [comment]
@EmilStenstrom  Hey there. [contributors-readme-action v2.1.1](https://github.com/marketplace/actions/contribute-list) has been released and fixed these bugs. Kindly update your workflow file.

Tysm for using this action and your feedbacks are much appreciated. For future release and also if you have liked the bot, kindly give a star ⭐ ( makes me also happy 😅) .

Sidenote: It was the ascii issue changed to utf-8

Closing this issue. Feel free to open it, if it didn't solved.
