### ISSUE TITLE
Linesbreaks after starting comments get converted

### ISSUE THREAD

**Issue by EmilStenstrom** [akhilmhdh/contributors-readme-action#23]
The bot seems to care about when type of linebreak there is after the starting comment where contributors are added. This means that the bot will battle with my editor, as my editor is set to use one type of linebreak, and contributor-readme-action is set to use another one. 

Example commit: https://github.com/EmilStenstrom/django-components/commit/2ff3b3291c0a4cf7a6de213beb5821386730c9fc

**Comment by akhilmhdh** [comment]
@EmilStenstrom  Oopz. Will fix all these issue by tonight. 
Thank you so much for reporting these  bugs. Much appreciated

**Comment by akhilmhdh** [comment]
@EmilStenstrom  Hey there. [contributors-readme-action v2.1.1](https://github.com/marketplace/actions/contribute-list) has been released and fixed these bugs. Kindly update your workflow file. 

Tysm for using this action and your feedbacks are much appreciated. For future release and also if you have liked the bot, kindly give a star ⭐ ( makes me also happy 😅) .

Closing this issue. Feel free to open it, if it didn't solved.

**Comment by EmilStenstrom** [comment]
Thank you! Will update the bot and just starred this project! :D
