### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by EmilStenstrom** [akhilmhdh/contributors-readme-action#33]
hi,

I enabled the action again, and now I get this weird error:

https://github.com/EmilStenstrom/django-components/runs/4095640771?check_suite_focus=true

Any clues?

**Comment by akhilmhdh** [comment]
@EmilStenstrom i think that error is due to lack of permission to put PR by taking a branch.

Ref: https://github.com/actions/first-interaction/issues/10

**Comment by akhilmhdh** [comment]
Most probably permission issue again. I guess even PR is having limitation. Easiest way that i found out to escape is to use personal access token. Should be last cause. Can you check ur repo permission

**Comment by EmilStenstrom** [comment]
I'm not sure where to look. There are no restrictions on who can create a PR currently. I'm not sure what else could be wrong?

What "resource" does the error message reference?

**Comment by akhilmhdh** [comment]
True. Let me see what's the root cause. Can you share me what all are the checks that you have put.

**Comment by EmilStenstrom** [comment]
![image](https://user-images.githubusercontent.com/224130/140300827-158e7220-8650-489f-a006-068faf9187e4.png)
![image](https://user-images.githubusercontent.com/224130/140300893-45ab0d1c-c601-4f58-818e-31367e5b4ea5.png)

**Comment by akhilmhdh** [comment]
@EmilStenstrom  I think i found out the issue: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

Something totally out of my hands i think so. Only alternative i find is using PAT

**Comment by akhilmhdh** [comment]
Hey @EmilStenstrom  closing this issue as its something out of my hand and due to inactivity 😅 . Feel free to open it if anything else is the root cause and I can definitely help you on it.

**Comment by EmilStenstrom** [comment]
Hi again. Sorry for not getting back to you. After we last spoke, I did get some PR:s posted. I did not change any settings, so I'm not sure what changed. Anyways, I got five (!) PR:s in quick succession: https://github.com/EmilStenstrom/django-components/pulls?q=is%3Apr+is%3Aclosed

I think it's best that I go back to a non-protected branch, and just use the action as it was intended to. Thank you so much for troubleshooting and trying out different solutions. 🙇

**Comment by akhilmhdh** [comment]
@EmilStenstrom i check ur workflow. Your running it on every branch on almost all events. I definitely won't recommend that. 

Github contributors are only in master right. Thats the issue. Run contributors on main only . It will then be only when there is a change in actual list and will be much more smaller may be even once in  a week.

**Comment by akhilmhdh** [comment]
Oh dang ill update my readme too

**Comment by akhilmhdh** [comment]
@EmilStenstrom Yosh updated readme. Run it against main branch only and your good to go. 

You wont even have the error in this issue because due to dependent bot token read_only issue. This will also reduce the PR generated **a lot** (let me bold that lot for you 😆 ).

**Comment by EmilStenstrom** [comment]
Ahhh. Thanks! I changed according to the instructions in the readme, and so far, so good! :)
