### ISSUE TITLE
Output `pr_id` does not return the right value

### ISSUE THREAD

**Issue by MrChocolatine** [akhilmhdh/contributors-readme-action#39]
Hey @akhilmhdh ! I was implementing your latest changes (thanks a lot for your reactivity!) and I was getting weird results when reusing your output `pr_id`.

It turns out, you are using the wrong key: `id` instead of `number`.

I know it is confusing, I would have done the same mistake, but that's GitHub's terminology ¯\_(ツ)_/¯ .

https://github.com/akhilmhdh/contributors-readme-action/blob/93b9712f2bff788e7fe3c58c53aeb1ea4da5d965/src/index.js#L173

If you are okay with this fix, I/you can reopen my linked PR #38 that I made too quickly 👍  .

**Comment by akhilmhdh** [comment]
Dang. My bad and good catch. Yup you can open that PR. Also @MrChocolatine can you bumb the readme too. I mean the readme has v2.3.1 i think. Can u bumb to next patch?

**Comment by MrChocolatine** [comment]
I will do that.

1. Fix
1. I just made another issue/suggestion to add to `.gitignore` the directory `/dist/`:
    https://github.com/akhilmhdh/contributors-readme-action/issues/40
1. New release and the update examples to the new version

**Comment by akhilmhdh** [comment]
Kindly dont tag or release it. Ill do that please.

**Comment by akhilmhdh** [comment]
Released. 😄

**Comment by MrChocolatine** [comment]
Everything works like a charm now, excellent, thanks again.
