### ISSUE TITLE
Unsigned commits block PRs on protected branch

### ISSUE THREAD

**Issue by MrChocolatine** [akhilmhdh/contributors-readme-action#42]
Hello again @akhilmhdh .

I might have spotted a small issue, quite blocking actually. A protected branch may require commits to be signed, therefore, as of now, when your GitHub Action creates a PR it will never be valid since the commit is not signed.

I haven't taken a deep look but by looking at this, it does not seems too complicated:
- https://gist.github.com/swinton/03e84635b45c78353b1f71e41007fc7c
- https://github.blog/2019-08-15-commit-signing-support-for-bots-and-other-github-apps/

Perhaps the solution would be:

1. To drop the customisation of the committer's email and name so that the default value is used? 🤔  Not sure about this.

https://octokit.github.io/rest.js/v18#repos-create-or-update-file-contents

> `committer` ..... The person that committed the file. Default: the authenticated user.

2. Or, following the point (1), to just use nothing (the default value = the authenticated user) if the inputs `committer_username` and `committer_email` have not been defined by the user.

**Comment by akhilmhdh** [comment]
I think it will be an issue only when the commit should have signature is enabled in protected section. But yah its a catch. Dropping is not a good thing. 

Yah need to go through this what are the options. Will soon release a patch to solve this.

**Comment by akhilmhdh** [comment]
They do have an option they can replace the commiter signature with there own signed bots/account if needed. Thats one solution. Let me try out in a dummy repo my options. Will get back to this

**Comment by akhilmhdh** [comment]
Hola @MrChocolatine .

Released a new patch that changed to verified commits. Yes, the easiest solution was to use the default `gh-action` as they are verified already. [v2.3.3](https://github.com/marketplace/actions/contribute-list) is released and now available.

In future I may change to verified `contrib-readme-bot`, but for now easiest fix was use default one. Thank you for putting this issue, closing this as this solves it. Feel free to open it .

**Comment by MrChocolatine** [comment]
Awesome, works like a charm! Thank you @akhilmhdh
