### ISSUE TITLE
Returns undefined, when sponsor is an organisation

### ISSUE THREAD

**Issue by Lissy93** [akhilmhdh/contributors-readme-action#45]
Heya @akhilmhdh,
Love your action, it's awesome!

This is a very minor issue, but when using to show a list of sponsors, if one of your sponsors is an organisation (instead of an individual user), then it shows up as undefined in the results table - [here's an example](https://github.com/Lissy93/dashy/blob/master/docs/credits.md) from my repo.

<p align="center"><a href="https://github.com/Lissy93/dashy/blob/master/docs/credits.md"><img src="https://user-images.githubusercontent.com/1862727/156430410-460fffbe-16ec-4567-8816-a7ead8121dc7.png" width="400" /></a></p>

From the docs, it looks like `sponsorEntity` can be either `User` or `Organization`, but [your query](https://github.com/akhilmhdh/contributors-readme-action/blob/master/src/query/getSponsorsList.gql)  only selects `User`. The `Organisation` also include all the fields you need, and with the same names (`name`, `login` and `avatarUrl`).

I would have submitted a PR myself, but I'm a noob at GH actions, and haven't managed to get it running locally 🤦‍♀️

**Comment by akhilmhdh** [comment]
hey @Lissy93  Thank you so much for using the action and also for your kind words 😃 

Ahhh got it. Thank for for sharing the repo link, and also the detailed cause of it. Will resolve and release a patch asap.

Hihi. GH action testing is still kinda tricky as you need to push to test. I am planning to rewrite the action in v4 to make local development and testing lot easier. And to make contribution easier.

**Comment by akhilmhdh** [comment]
Hey @Lissy93 

I was actually going though this bug and ran this query in explorer and found out that GitHub is giving null. Weird, i must say.

![Screenshot 2022-03-04 at 10 24 18 PM](https://user-images.githubusercontent.com/31166322/156806366-9d871021-c853-4206-a48f-9ea4d05893a0.png)

So i checked your sponser list in profile and actually there is also same case 😅 

![Screenshot 2022-03-04 at 10 28 47 PM](https://user-images.githubusercontent.com/31166322/156806580-3723985c-0265-4b6c-b78b-2a7f4e9c6652.png)

Check out the last person. I didn't know that it was nullable. Anyways ill do a filter to clear nullable ones and add the missing org query also.

**Comment by akhilmhdh** [comment]
Hey @Lissy93 I have released new patch version that resolves this.

Checkout [contributors-readme-actionv2.3.4](https://github.com/marketplace/actions/contribute-list)

I am closing this issue as I assume this will resolve it. If not or if you have any trouble feel free to open the issue.
