### ISSUE TITLE
If there is readme.md and readme.zh-CN.md How should be configured

### ISSUE THREAD

**Issue by kailong321200875** [akhilmhdh/contributors-readme-action#46]
If there is readme.md and readme.zh-CN.md How should be configured

**Comment by akhilmhdh** [comment]
Hey @kailong321200875 . Sorry for the delayed reply.

If you have two readme the easiest way to show list in both is run two actions and using `readme_path` option point one towards `readme.md` and other one towards `readme.zh-CN`

**Comment by kailong321200875** [comment]
> Hey @kailong321200875 . Sorry for the delayed reply.
> 
> If you have two readme the easiest way to show list in both is run it as two actions and using `readme_path` option point one towards `readme.md` and other one towards `readme.zh-CN`

OK，thank you
