### ISSUE TITLE
Names with brackets `<` and `>` get interpreted as HTML tag

### ISSUE THREAD

**Issue by EmilStenstrom** [akhilmhdh/contributors-readme-action#49]
Hi! I have a contributor with angle brackets like this: `<USER NAME HERE>`. This name shows up empty in the readme. I think it would be a good idea to escape the user name to avoid breaking the readme.

![image](https://user-images.githubusercontent.com/224130/179015765-0aad0760-37e2-437f-b8ed-28bdd854497d.png)

**Comment by akhilmhdh** [comment]
Good catch. Soon ill be applying a templating engine in v4. 

But yah ill release a patch immediately

**Comment by akhilmhdh** [comment]
Hey @EmilStenstrom . I have released patch for this action. [Contributors-Readme-Action v2.3.5](https://github.com/marketplace/actions/contribute-list). 

Closing this issue as its resolved. Feel free to re-open if its not resolved.

**Comment by EmilStenstrom** [comment]
Works great, thanks again @akhilmhdh! :)

**Comment by EmilStenstrom** [comment]
Not so fast. It seems to re-escape the already escaped characters each time it's run. Check this PR: https://github.com/EmilStenstrom/django-components/pull/167/commits/8f76c3f748d4ed4a788dbe268db999f0e72b67a4

**Comment by akhilmhdh** [comment]
Ohhh dang @EmilStenstrom my bad. Will resolve it. I missed that case

**Comment by akhilmhdh** [comment]
hey @EmilStenstrom released a patch v2.3.6 that fixed the re-encoding issue. Let me know if any issue with it.
