### ISSUE TITLE
Add images to README

### ISSUE THREAD

**Issue by 0dminnimda** [akhilmhdh/contributors-readme-action#51]
It feels like the readme will get much better if there would be some images/examples.
As someone who just found this I wanna quckly see first if I want this thing to change my readme

**Comment by akhilmhdh** [comment]
Hi @0dminnimda.

Sorry, I didn't get you. You mean the final result of how the readme be like, that image

**Comment by 0dminnimda** [comment]
If I understand correctly this repo helps to add a "Contributirs" section to the readme
I want to see how it'll look

**Comment by akhilmhdh** [comment]
Yah. Basically its a Github Action. And all you need do is add a config file to your repo and that's the instruction in readme.

Let me know what got you confused. I'll work on that definitely. If your new to Github actions would recommend to go through below references.

Ref: 
https://github.com/features/actions
https://docs.github.com/en/actions

**Comment by 0dminnimda** [comment]
I'm not confudes by actions.
I can't find depiction of the end result actions will have on the hypothetical readme
You want to sell with images, you know ;)

**Comment by 0dminnimda** [comment]
For exmaple you can immediately see how all-contributors will look with [their contributers in thir readme](https://github.com/all-contributors/all-contributors#contributors-)
You don't have to use your contributors and don't have to add it in markdown. But there needs to be an example

**Comment by akhilmhdh** [comment]
Ahhh. Ok got it. Will update the readme

**Comment by akhilmhdh** [comment]
Hey @0dminnimda , I have updated readme with an image on final result. 

Thank you for your feedback, much appreciated. Feel free to raise an issue if you come across any trouble

**Comment by 0dminnimda** [comment]
Yeah, that's better 👍
