### ISSUE TITLE
Exlusion list

### ISSUE THREAD

**Issue by xobotyi** [akhilmhdh/contributors-readme-action#52]
It would be great to have exlusion list, as some of bots are not fitered by default filter, 4ex: https://github.com/react-hookz/web

It seems that @semantic-release-bot and @lint-action are registered as regular users, but not bots, and therefore are not filterbale by type.

**Comment by akhilmhdh** [comment]
Hey @xobotyi . You can do an exclusion, by just adding in format `-<username>` and these will get removed.

Or did u mean to store like an ignore list in a file

**Comment by xobotyi** [comment]
🤔 Haven't seen it in docs (maybe I was inattentive).

Actually I'd expect an option within `with` section of action config, but current approach is also fine for me, as I'm planning to have only one section. 

Nevertheless it may be a worth option to implement as maybe I'm not alone in that confusion🙃

**Comment by xobotyi** [comment]
Yup, read the docs not thorough enough🙈

Maybe it is worth adding separate section after "how to add more users" with explicit name like "how to exclude users from list"

**Comment by akhilmhdh** [comment]
😄  gotcha. Thanks for the feedback. Yah your right, the exclusion part needs a but more attention. Will update the readme soon.

 I am planning to soon release v4 which will be much more powerful and customizable. WIll consider this on the next major release as an easier solution.

**Comment by akhilmhdh** [comment]
Hey @xobotyi , I have updated the readme with the walk through and added boldness to get attention to key points. 

Feel free to raise an issue if you come across. Once again thank you for feedback 😃  . Closing this issue for now
