### ISSUE TITLE
Where can i type parameters

### ISSUE THREAD

**Issue by samslow** [akhilmhdh/contributors-readme-action#6]
on the README.md
```md
Optional parameters
To change the image size inside the box
imageSize:100
Default value is 100x100px

To change the number of columns in a row
columnsPerRow:6
Default value is 6
````

but idk where can i arrange this options 

actions script or read me?

**Comment by akhilmhdh** [comment]
Action script. 
Her you go the doc ![https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action]
Scroll a bit down to the section Testing out your action in a workflow.
```
with:
        columnsPerRow: 6
```
These are the places where variables are applied.

I'll also update the readme regarding this.
