### ISSUE TITLE
Missing contributor & contributor name null

### ISSUE THREAD

**Issue by xMikux** [akhilmhdh/contributors-readme-action#60]
Hi, when I using this action, I notice contributors name some of is null like this.

![image](https://user-images.githubusercontent.com/26039249/210178035-a3a29ae5-b6ae-47fe-8763-cc9daf4d259c.png)

And one of contributor missing.

**Comment by xMikux** [comment]
PR of this issues https://github.com/xMikux/ModsTranslationPack/pull/101

and also I notice when I using ``commit_message`` and ``pr_title_on_protected`` with chinese message, it won't appear.

**Comment by akhilmhdh** [comment]
Ohhhhh interesting. I'll definitely take a look at this and resolve it

**Comment by xMikux** [comment]
oh wait, I put it ``commit_message `` and ``pr_title_on_protected`` on env, that is why it is not using.

**Comment by reinder** [comment]
I'm having the same issue, if a contributor doesn't have its name set in their profile it displays `Null`

Suggestion: if name is null use username instead.

**Comment by akhilmhdh** [comment]
@reinder ill raise a patch for as soon as possible

**Comment by melroy89** [comment]
> @reinder ill raise a patch for as soon as possible

Any update? It's still happening.

**Comment by melroy89** [comment]
I fixed it myself: https://github.com/akhilmhdh/contributors-readme-action/pull/77
