### ISSUE TITLE
set-output command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by mauvehed** [akhilmhdh/contributors-readme-action#67]
One of my recent runs of this action produced the following message. 

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It looks like GitHub has postponed the deprecation of this for an unknown time period, but the original date was May 31st, 2023. 

> ~We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.~ Our telemetry shows significant usage of these commands. Given the number of impacted customers we are postponing the removal.

Either way, the project should prepare to move away from this before it suddenly breaks all further usage of this action.

**Comment by dtcMLOps** [comment]
We need this + update the runtime to node 20

**Comment by akhilmhdh** [comment]
@dtcMLOps got it. Ill try to cover it up by this week

**Comment by dtcMLOps** [comment]
Hi @akhilmhdh you can fin my PR for this issue here #74
