### ISSUE TITLE
Missing 'tbody' in the generated 'table'

### ISSUE THREAD

**Issue by hwhsu1231** [akhilmhdh/contributors-readme-action#68]
### Problem Description

I found that there's no `<tbody></tbody>` inside the `<table></table>` generated by this GitHub Action.

```md
<!-- readme: contributors -start -->
<table>
<tr>
    <td align="center">
        <a href="https://github.com/hwhsu1231">
            <img src="https://avatars.githubusercontent.com/u/71438617?v=4" width="50;" alt="hwhsu1231"/>
            <br />
            <sub><b>Haowei Hsu</b></sub>
        </a>
    </td></tr>
</table>
<!-- readme: contributors -end -->
```

Although it looks fine in GitHub or some Markdown Editors, there will be a problem when I upload a `README.md` which has this form of `<table></table>` to Crowdin. Take an issue I recently encountered while testing [andrii-bodnar/action-crowdin-contributors](https://github.com/andrii-bodnar/action-crowdin-contributors) for example.

Origianally, I used `v1.0.2` version of this GitHub Action to generate a Crowdin Contributors List. The generated HTML table is as follow:

<details><summary>Click to expand codes</summary>

```md
<!-- CROWDIN-CONTRIBUTORS-START -->
<table>
  <tr>
    <td align="center" valign="top">
      <a href="https://crowdin.com/profile/hwhsu1231"><img alt="logo" style="width: 50px" src="https://crowdin-static.downloads.crowdin.com/avatar/15619673/medium/2c1c17f04c7d3131cd44cba220d3ab93.png" />
        <br />
        <sub><b>Haowei Hsu (hwhsu1231)</b></sub></a>
      <br />
      <sub><b>2334 words</b></sub>
      <br /><sub><b><code title="Chinese Simplified">zh-CN</code></b>, <b><code title="Chinese Traditional">zh-TW</code></b></sub>
    </td>
  </tr>
</table>
<!-- CROWDIN-CONTRIBUTORS-END -->
```

</details>

However, an error showed up when I tried to upload this `README.md` to Crowdin:

<details><summary>Click to expand logs</summary>

```md
D:\Test\test-crowdin-readme>crowdin upload --branch test
[OK] Fetching project info
[SKIPPED] Branch 'test' already exists in the project
[ERROR] File 'test\README.md'
[ERROR] Wrong parameters:
<key: storageId, code: fileInvalid, message: An unknown error occurred while importing the file.>
[ERROR] Current execution finished with errors

D:\Test\test-crowdin-readme>
```

</details>

After reporting to Crowdin Support Team, they fix this issue by upgrading this GitHub Action to [`v1.0.3`](https://github.com/andrii-bodnar/action-crowdin-contributors/releases/tag/v1.0.3), in which they add `<tbody></tbody>` into `<table></table>`. The newly generated table is as follow:

<details><summary>Click to expand codes</summary>

```md
<!-- CROWDIN-CONTRIBUTORS-START -->
<table>
  <tbody>
    <tr>
      <td align="center" valign="top">
        <a href="https://crowdin.com/profile/hwhsu1231"><img alt="logo" style="width: 50px" src="https://crowdin-static.downloads.crowdin.com/avatar/15619673/medium/2c1c17f04c7d3131cd44cba220d3ab93.png" />
          <br />
          <sub><b>Haowei Hsu (hwhsu1231)</b></sub></a>
        <br />
        <sub><b>2334 words</b></sub>
        <br /><sub><b><code title="Chinese Simplified">zh-CN</code></b>, <b><code title="Chinese Traditional">zh-TW</code></b></sub>
      </td>
    </tr>
  </tbody>
</table>
<!-- CROWDIN-CONTRIBUTORS-END -->
```

</details>

Therefore, I hope this GitHub Action, [akhilmhdh/contributors-readme-action](https://github.com/akhilmhdh/contributors-readme-action), can fix this issue as well. That is, I hope it can generate the following form of table:

```md
<!-- readme: contributors -start -->
<table>
  <tbody>
    <tr>
      <td align="center">
        <a href="https://github.com/hwhsu1231">
          <img src="https://avatars.githubusercontent.com/u/71438617?v=4" width="50;" alt="hwhsu1231"/>
          <br />
          <sub><b>Haowei Hsu</b></sub>
        </a>
      </td>
    </tr>
  </tbody>
</table>
<!-- readme: contributors -end -->
```

### Versions

akhilmhdh/contributors-readme-action@v2.3.6

**Comment by akhilmhdh** [comment]
Hey @hwhsu1231 

Sorry for the long delay. But v2.3.10 should resolve this
