### ISSUE TITLE
GITHUB_TOKEN?

### ISSUE THREAD

**Issue by ddnexus** [akhilmhdh/contributors-readme-action#69]
I read the little doc... and the issues, but I've found no mention on what the GITHUB_TOKEN is supposed to be. I can guess it, but nevertheless a single little paragraph explaining how to create and use it would save a lot of time of guessing and try and error.

I would like the README to be automatically updated (i.e. no PR). How that is supposed to be configured? Again: a simple example in the doc would greatly improve the usability of this project.

Thanks

**Comment by AmosHuKe** [comment]
https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Comment by akhilmhdh** [comment]
And i am not sure what you meant on how to configure without PR its right in the first steps.
