### ISSUE TITLE
Can i control header name ?

### ISSUE THREAD

**Issue by samslow** [akhilmhdh/contributors-readme-action#7]
this actions support keword 'Contributor'

but i want customize that name.

for example, Teammates, Friend ··· 

can you add this feature ?

**Comment by akhilmhdh** [comment]
@samslow Thats a great feature. Ill definitely add it by today and release it. Thank you for your feedback. 😃

**Comment by akhilmhdh** [comment]
Hey @samslow I have released a new version. Do check it out. Fixed the doc and some bugs too. Closing this issue. 

New Release :
![Contributors-Readme-Action v1.1](https://github.com/marketplace/actions/contribute-list)

Looking forward to more feature suggestions and contributions. 😄

**Comment by samslow** [comment]
wow you so fast
