### ISSUE TITLE
Can we add it to any other .md file instead of README file?

### ISSUE THREAD

**Issue by atharwa-24** [akhilmhdh/contributors-readme-action#8]
If its possible then how to do so.

**Comment by akhilmhdh** [comment]
@atharwa-24 Hi there, Currently i am using GitHub readme API to fetch directly the readme file. So currently that ans is not possible. But if you meant by changing the readme.md to some other positioned .md thats a great feature. Ill definitely add it soon.

**Comment by akhilmhdh** [comment]
@atharwa-24 Hey man. Checkout the new [v2.0](https://github.com/marketplace/actions/contribute-list?version=v2.0). I have added a parameter to change your readme.md. Thank you for your feedbacks, closing this issue feel free to open it again if there's any issue

**Comment by atharwa-24** [comment]
Thanks!!!
