### ISSUE TITLE
 Ordering Contributors

### ISSUE THREAD

**Issue by nhcarrigan** [akhilmhdh/contributors-readme-action#9]
I did not see it possible in the docs, but it would be nice to have a config setting that allowed us to set "priority" contributors who appear first in the generated table.

**Comment by akhilmhdh** [comment]
@nhcarrigan currently i am using GitHub contributors API that gives the first 500 contributors in order of there commits. Can you please tell me what you meant by priority by an example. I would be glad to implement it.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/91526272-17413f80-e8b8-11ea-963b-4b5f96296cab.png)

This is an example from a project I am collaborating on. `bradtaniguchi` and I are the primary collaborators - would it be possible to add a config setting to say "list these users first in the table"?

**Comment by akhilmhdh** [comment]
ohhhhh currently as its based GitHub API the list based on most contributions made. But you want to override to set some core members to be in first category. Wow, thats actually a cool idea. I would definitely add this new feature. Give me sometime.

**Comment by akhilmhdh** [comment]
@nhcarrigan Hi man. So a feature that I am thinking of is what about we make contributors list into much more division like Core team, and others as contributors like that instead of ordering them at first. Can you please give your opinion on that like will a division like that be nice or not.

**Comment by nhcarrigan** [comment]
Yes, I think that would be an excellent approach!

**Comment by akhilmhdh** [comment]
Thanks man 😄 , I will work on it asap.

**Comment by nhcarrigan** [comment]
I haven't looked into the GitHub API much, but it may be possible to grab a repository's collaborators or organisation members for the "core team" section. 🤔

**Comment by akhilmhdh** [comment]
yah @nhcarrigan i think so but organization members can't be added right. I mean consider a big organization, each of them will be working on small projects independently right. Well i think i need to check the new updated GitHub API. To optimize and restructure everything.

**Comment by akhilmhdh** [comment]
@nhcarrigan checkout [2.0](https://github.com/marketplace/actions/contribute-list?version=v2.0). The usage of the action has changed kindly go through the readme. You can easily change the order now and prioritize some people. If this solved your issue kindly close it. 😄

**Comment by nhcarrigan** [comment]
Looks good to me!
